# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/dtype_diet/',
                'doc_host': 'https://noklam.github.io',
                'git_url': 'https://github.com/noklam/dtype_diet/tree/master/',
                'lib_path': 'dtype_diet'},
  'syms': {'dtype_diet.core': {}}}