# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"count_errors": "00_core.ipynb",
         "map_dtypes_to_choices": "00_core.ipynb",
         "AsType": "00_core.ipynb",
         "Row": "00_core.ipynb",
         "get_smallest_valid_conversion": "00_core.ipynb",
         "get_improvement": "00_core.ipynb",
         "report_on_dataframe": "00_core.ipynb",
         "optimize_dtypes": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://noklam.github.io/dtype_diet/"

git_url = "https://github.com/noklam/dtype_diet/tree/master/"

def custom_doc_links(name): return None
