# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://noklam.github.io/dtype_diet/"

git_url = "https://github.com/noklam/dtype_diet/tree/master/"

def custom_doc_links(name): return None
